<a href="https://colab.research.google.com/github/mintra-tippayaratsontorn/Multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Function

```python
def function_name(_Input_) : 
    do_something with _Input_ to get _Output_
    return _Output_
```

*เอียง*

```backtick กดค้างตรงที่เปลี่ยนภาษา

function มีส่วนสำคัญทั้งหมด 4 ส่วน
  1. บอก python ว่าเราจะเขียนฟังก์ชัน ชื่ออะไร def function_name(): (ขาดไม่ได้)
  2. กำหนดตัวแปรที่จะเป็น input output (ขาดได้)
  3. ส่นประมวลผล do_something with _Input_ to get _Output_ (ขาดไม่ได้)
  4. ส่วน output return _Output_ (ขาดได้)

เราใช้เว้นวรรค (indent) เพื่อบอกขอบเขตของ code

หน้าที่คือรับ input และทำตามกระบวนการละก็ได้ Output ออกมา

### สร้างฟังก์ชัน

In [ ]:
def print_name(name,surname,ID) : # input มีกี่ตัวก็ได้/ไม่มีก็ได้
  st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
  return st
print('outside function')

outside function


### เรียกใช้ฟังก์ชัน

In [ ]:
print_name('มินตรา','ทิพยรัตน์สุนทร','623020041-2')

'ชื่อ มินตรา นามสกุล ทิพยรัตน์สุนทร รหัส 623020041-2'

In [ ]:
output_string = print_name('มินตรา','ทิพยรัตน์สุนทร','623020041-2')
print(output_string)

ชื่อ มินตรา นามสกุล ทิพยรัตน์สุนทร รหัส 623020041-2


### ฟังก์ชันไม่จำเป็นต้องมี output

In [ ]:
def print_name2(surname,ID,name) :
  st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
  print(st)

In [ ]:
print_name2('มินตรา','ทิพยรัตน์สุนทร','623020041-2')

ชื่อ 623020041-2 นามสกุล มินตรา รหัส ทิพยรัตน์สุนทร


In [ ]:
op2 = print_name2('มินตรา','ทิพยรัตน์สุนทร','623020041-2')

ชื่อ 623020041-2 นามสกุล มินตรา รหัส ทิพยรัตน์สุนทร


In [ ]:
print(op2)

None


### ฟังก์ชันไม่จำเป็นต้องมี input

In [ ]:
def Pi() :
  return 3.14159265359

In [ ]:
# คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่าศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

7.0685834705775

In [ ]:
def print_my_name():
    print('มินตรา ทิพยรัตน์สุนทร 623020041-2')

In [ ]:
print_my_name()

มินตรา ทิพยรัตน์สุนทร 623020041-2


### input ของ function ใน python มี2แบบ input ที่จำเป็นต้องใส่ (มีค่า default)

### เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name, surname, ID, grade='F'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [ ]:
print_2lines_default('มินตรา','ทิพยรัตน์สุนทร','623020041-2')

ชื่อ มินตรา นามสกุล ทิพยรัตน์สุนทร รหัส 623020041-2
เกรดวิชา Multivariate >>> F


In [ ]:
print_2lines_default('มินตรา','ทิพยรัตน์สุนทร','623020041-2','A')

ชื่อ มินตรา นามสกุล ทิพยรัตน์สุนทร รหัส 623020041-2
เกรดวิชา Multivariate >>> A


### เราสามารถเรียกฟังก์ชันโดยใช้ชื่อตัวแปรของฟังก์ชันช่วยได้

In [ ]:
print_name2(name='มินตรา' , surname='ทิพยรัตน์สุนทร' , ID='623020041-2')

ชื่อ มินตรา นามสกุล ทิพยรัตน์สุนทร รหัส 623020041-2


HW3 ให้เขียน function คำนวณจำนวณวินาทีจากเวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [7]:
def function_q (times):
    q = f'เวลาทั้งหมด -> {times}'
    print(q)
    times_sp = times.split('-')
    h = int(times_sp[0])*3600
    m = int(times_sp[1])*60
    s = int(times_sp[2])
    aq = h+m+s
    print(f'คำนวณเป็นวินาทีได้เท่ากับ {aq} วินาที')

In [8]:
function_q('14-15-31')

เวลาทั้งหมด -> 14-15-31
คำนวณเป็นวินาทีได้เท่ากับ 51331 วินาที


In [9]:
function_q('13-00-01')

เวลาทั้งหมด -> 13-00-01
คำนวณเป็นวินาทีได้เท่ากับ 46801 วินาที


In [10]:
function_q('05-49-44')

เวลาทั้งหมด -> 05-49-44
คำนวณเป็นวินาทีได้เท่ากับ 20984 วินาที


In [11]:
function_q('00-00-16')

เวลาทั้งหมด -> 00-00-16
คำนวณเป็นวินาทีได้เท่ากับ 16 วินาที


# Numpy

เป็น package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

num + py ย่อมาจาก Number-Numberical + pythion

การใช้ package
1. ```import``` ```ชื่อ package``` # เรียกใช้package
2. ```ชื่อpackage``` , ```ชื่อ function``` #เรียกใช้function

In [2]:
import numpy

data structure -> array

สร้าง array (numpy array)

In [4]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print (mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [5]:
mat_ex1[1,1]  # [แถว(แนวนอน),หลัก(แนวตั้ง)] และการนับต้องเริ่มจาก0ไปเรี่อยๆ

0.1

ถ้าไม่มี numpy array 

In [6]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [18]:
list_ex1[1][1]  #วิธีเลือกตัวในlistออกมา

0.1

In [20]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Martrix Operations

data 2 แบบ -> matrix (2D array) และ scalar (ตัวเลขค่าคงที่)

In [21]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


### การบวก/ลบ matrix เอาตัวเลขที่อยู่ตำแหน่งเดียวกันบวก/ลบกัน

(ขนาดของ matrix ต้องเหมือนกัน)

In [27]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [28]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [29]:
mat_ex1 + mat_ex0 

ValueError: ignored

### การตรวจสอบขนาดของ matrix

In [30]:
mat_ex3.shape

(2, 3)

In [31]:
mat_ex3.shape[0]  #ดูขนาดแถวของ matrix

2

### การคูณ Matrix (แถวคูณหลัก)
(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)

dot product((AAA,x),(x,ZZZ)) = (AAA,ZZZ)

In [35]:
mat_ex1 * mat_ex2 # การคูณ matrix ไม่ใช้วิธีแบบนี้

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [40]:
numpy.dot(mat_ex1,mat_ex2) # ต้องtransposeก่อน

ValueError: ignored

In [42]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลัก/กลับหลักเป็นแถว
```matrix.T```

In [44]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [45]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [43]:
numpy.dot(mat_ex1,mat_ex2.T)  # (2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [46]:
numpy.dot(mat_ex1.T,mat_ex2)  # (3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse Matrix (รูปและคำอธิบาย)

~Pandas~